### ISSUE TITLE
macOS, Window not appear

### ISSUE THREAD

**Issue by simon300000** [ci010/VoxeLauncher#17]
os: Darwin, macOS 10.13.5
node: v10.1.0
npm: 6.0.1

After `npm i`, `npm run dev`,
No window appear.

Tried install use 'cnpm i'
No help.

Found two error in log during `npm run dev`:

┏ Electron -------------------

  An error occured when we load module [versions].
  TypeError: Cannot read property 'release' of undefined
      at Store.update (/Users/simon3000/GitHub/ILauncher/dist/electron/main.js:17416:56)
      at wrappedMutationHandler (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:699:13)
      at commitIterator (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:391:7)
      at Array.forEach (<anonymous>)
      at /Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:390:11
      at Store._withCommit (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:497:3)
      at Store.commit (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:389:8)
      at Store.boundCommit [as commit] (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:337:19)
      at Object.local.commit (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:653:13)
      at Store._callee2$ (/Users/simon3000/GitHub/ILauncher/dist/electron/main.js:17450:41)
  Error: UUID cannot be undefined
      at Store.fetch (/Users/simon3000/GitHub/ILauncher/dist/electron/main.js:17298:30)
      at Array.wrappedActionHandler (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:706:23)
      at Store.dispatch (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:428:15)
      at Store.boundDispatch [as dispatch] (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:334:21)
      at Object.local.dispatch (/Users/simon3000/GitHub/ILauncher/node_modules/vuex/dist/vuex.common.js:636:20)
      at Store._callee4$ (/Users/simon3000/GitHub/ILauncher/dist/electron/main.js:16861:48)
      at tryCatch (/Users/simon3000/GitHub/ILauncher/dist/electron/main.js:8982:40)
      at Generator.invoke [as _invoke] (/Users/simon3000/GitHub/ILauncher/dist/electron/main.js:9216:22)
      at Generator.prototype.(anonymous function) [as next] (/Users/simon3000/GitHub/ILauncher/dist/electron/main.js:9034:21)
      at step (/Users/simon3000/GitHub/ILauncher/dist/electron/main.js:115:30)
  
┗ ----------------------------

┏ Electron -------------------

  { error: 'UnauthorizedOperationException',
    errorMessage: 'User not authenticated' }
  
┗ ----------------------------

**Comment by ci010** [comment]
emmmm interesting

**Comment by simon300000** [comment]
@ci010 要不你把你的版本告诉我，我装了试试？

**Comment by ci010** [comment]
我这边应该就是用的store refactor 上最新的，不过load好像是有点问题。。。最近又没太有时间修

**Comment by simon300000** [comment]
其实我说的是node版本→_→

**Comment by ci010** [comment]
这边是8的lts版本

**Comment by simon300000** [comment]
估计和node的版本有一些关系，node v8.9.3, 现在窗口出现了，但是还是有别的问题。
控制台里面有很多error，似乎是webpack出来的
我估计是因为electron自带的node的版本不合适，我等等升级一下electron试试
<img width="1212" alt="2018-05-28 11 33 44" src="https://user-images.githubusercontent.com/12656264/40596084-297bbdea-626b-11e8-8145-b4864fa2e23a.png">

**Comment by ci010** [comment]
You can try new version if you have time.
